CREATE TABLE IF NOT EXISTS SMN (
    LOT TEXT,
    ROUTE TEXT,
    OPERATION INTEGER,
    SPS_NAME TEXT,
    EQUIPMENT TEXT,
    OPERATOR TEXT,
    TIME_STAMP_UTC DATETIME,
    SORTER_JOB_COMPLETE_INCON_SRC INTEGER
);