:rootpath: ./

= Data Analytics in Logistics: SMN Analyse
:toc:
:toclevels: 4
:toc-title: Inhaltsverzeichnis
:sectnums:
:icons: font

== Einführung

Bereitgestellt wird ein Datensatz mit dem Protokoll der Prozessierungsschritte von Losen in einer Halbleiterfabrik. Er enthält insgesamt **6.360.000 Zeilen**. Ein Los besteht aus bis zu 25 Wafern, die gemeinsam in einem FOUP transportiert werden. In regelmäßigen Abständen wird in gesonderten Sortierschritten die sog. „Losintegrität“ geprüft, um sicherzustellen, dass sich tatsächlich jeder Wafer in dem Slot des FOUPs befindet, in dem man ihn erwartet.

Folgende Punkte sind bei der Interpretation der Daten zu beachten:

* ROUTE: Eine Route beschreibt die Abfolge der Prozessierungsschritte, die ein Los in der Fabrik durchläuft. Sie definiert die Technologie, nach der ein bestimmtes Produkt entsteht.
* OPERATION: Eine Operation ist ein Prozessierungsschritt innerhalb einer Route. Die Operations sollten in zeitlich aufsteigender Folge absolviert werden.
* SPS_NAME: Dies ist der Typ des Prozessierungsschritts. Sortierschritte sollten mit „ID“ beginnen.
* EQUIPMENT: Dies ist der Typ des Tools, das in diesem Prozessierungsschritt eingesetzt wird. Bei Sortierschritten sollte er „AUTP“ lauten. Messschritte sind mit „MESP“ gekennzeichnet, sie dienen der Qualitätssicherung und können ggf. ausgelassen werden.
* SORTER_JOB_COMPLETE_INCON_SRC: Dies ist das Ergebnis eines Sortierschritts. Ein Wert größer als 1 kennzeichnet eine Losintegritätsverletzung.

Diesen Datensatz gilt es hinsichtlich der Prozessoptimierung sowie weiteren Auffälligkeiten zu analysieren.

<<<
include::01_database_cleanup/_section.adoc[]

<<<
include::02_understanding_the_data/_section.adoc[]

