UPDATE SMN SET SORTER_JOB_COMPLETE_INCON_SRC = NULL WHERE SORTER_JOB_COMPLETE_INCON_SRC = '';

INSERT INTO SMN
SELECT
    LOT,
    ROUTE,
    CAST(OPERATION AS INTEGER),
    SPS_NAME,
    EQUIPMENT,
    OPERATOR,
    datetime(TIME_STAMP_UTC),
    iif(SORTER_JOB_COMPLETE_INCON_SRC != '', CAST(SORTER_JOB_COMPLETE_INCON_SRC AS INTEGER), NULL)
FROM temp;

CREATE INDEX LOT_IDX ON SMN(LOT);
CREATE INDEX ROUTE_IDX ON SMN(ROUTE);

DROP TABLE temp;