all: measurements1.csv

measurements1.csv:
	$(info "====================================")
	$(info "Generating File measurements.csv....")
	touch folder1/measurements.csv
	@echo "Finished generating measurements.csv"
	$(info "This will be printed before the 'Finished' Message!")
