:path: 01_database_cleanup

ifdef::rootpath[]
:imagesdir: {rootpath}{path}
endif::rootpath[]

== Datenbereinigung: Konzentration auf die aussagekräftigsten Daten

Um die Analyseergebnisse zu optimieren und aussagekräftige Schlussfolgerungen aus den Daten zu ziehen, wurde eine Datenbereinigung durchgeführt. Dabei wurden Datensätze herausgefiltert, die aufgrund von Inkonsistenzen oder fehlender Relevanz für die Analyse untauglich waren.

=== Auswahl der frequentiertesten Routen

Damit unsere Analysen auf einer ausreichenden Datengrundlage beruhen, werden Routen, die nur von wenigen Losen durchlaufen werden herausgefiltert.
Es werden die am wenigsten frequentierten 50 % der Routen entfernt. Dabei werden Routen entfernt, die von weniger als
**
include::select_limit_unfrequent_routes.csv[]
Losen**
durchlaufen werden entfernt, wodurch
**
include::count_items_unfrequent_routes.csv[]
Routen**
und somit
**
include::count_rows_unfrequent_routes.csv[]
Zeilen**
entfernt werden.


=== Entfernen von unvollständig dokumentierten Losen

Da unser Datensatz ab dem 22.09.2022 alle Vorgänge dokumentiert, die Produktion allerdings schon davor lief, gibt es im Datensatz Lose, die vor Beginn der Dokumentierung begonnen wurden. Diese sind jene Lose deren erste Erscheinung einen Operations-Counter größer als 1 hat. Dabei handelt es sich um **
include::count_items_lots_that_do_not_start_with_operation_1.csv[]
Lose** und es werden **
include::count_rows_lots_that_do_not_start_with_operation_1.csv[]
Zeilen** aus der Datenbank entfernt.

// === Entfernen aller Lose, die mehrere Routen durchlaufen
//
// Die Daten enthalten Lose, die mehrere Routen durchlaufen. Da ein Los dabei einzelne Operationen von einer Route mit Schritten einer anderen Route vermischt, werden diejenigen Lose, die mehrere Routen durchlaufen aus den Daten entfernt. Es handelt sich dabei um **
// include::count_items_lots_that_run_several_routes.csv[]
// Lose**, wodurch **
// include::count_rows_lots_that_run_several_routes.csv[]
// Zeilen** entfernt werden.

=== Entfernen von kurzen Routen
Routen mit wenigen Operationen wurden entfernt, um Routen mit unzureichender Datengrundlage aus der Analyse auszuschließen. Dabei wurde ein Schwellwert von 100 Operationen gewählt.
Es werden **
include::count_items_short_routes.csv[]
Routen** und damit **
include::count_rows_short_routes.csv[]
Zeilen** entfernt.

=== Entfernen aller Operationen mit Inkonsistenzen in Operationszähler und Zeitstempel
Fehlt noch (Probleme mit Query)
// TODO _count_rows_unordered_operations

'''
Durch die Anwendung dieser Filterkriterien wurde der ursprüngliche Datensatz bereinigt. Durch diese Bereinigungsmaßnahmen reduziert sich die Datenmenge auf **
include::count_leftover_rows.csv[]
verbleibende Zeilen**, die für die weitere Analyse verwendet werden können. Durch diese Datenbereinigung erhoffen wir uns qualitativ bessere Ergebnisse in der weitergehenden Analyse.