all: measurements2.csv

measurements2.csv:
	$(info "====================================")
	$(info "Generating File measurements.csv....")
	touch folder2/measurements.csv
	@echo "Finished generating measurements.csv"
	$(info "This will be printed before the 'Finished' Message!")
